# methylKit
# https://github.com/al2na/methylKit
# methylKit v0.99.2 commit 0a5581c
FROM rocker/r-ver:4.0.0

# Установка необходимых пакетов и зависимостей
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        zlib1g-dev \
        libxml2-dev \
        libbz2-dev \
        liblzma-dev \
        libpcre3-dev \
        libicu-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        git-core \
        python3 \
        python3-pip

# Установка R пакетов с CRAN
RUN R -e "install.packages(c('devtools', 'BiocManager'), dependencies=TRUE)"

# Обновление установленных R пакетов
RUN R -e "update.packages(ask = FALSE, checkBuilt=TRUE)"

# Явная установка matrixStats (необходима для некоторых зависимостей Bioconductor)
RUN R -e "install.packages('matrixStats', repos = 'http://cran.rstudio.com/')"

# Установка methylKit с GitHub
RUN R -e "devtools::install_github('al2na/methylKit', build_vignettes=FALSE, repos=BiocManager::repositories(), dependencies=TRUE)"

# Установка pysam для Python
RUN pip3 install pysam

# Копирование скриптов на Python и R в контейнер
COPY process_bam.py /home/process_bam.py
COPY methyl_analysis.R /home/methyl_analysis.R

WORKDIR /home